site_name: Kamran Ali (Data Scientist, Data Analyst)
site_description: A collection of my Projects and work experience
site_author: Kamran Ali
# site_url: https://kamranali.github.io/Portfolio


theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: blue
      accent: indigo
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/data.png  # Optional: add your logo
  favicon: favicon.ico  # Optional: add your favicon
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - search.highlight
    - search.share
    - content.code.annotate
    - content.tabs.link

nav:
  - Home: index.md
  - About: about.md
  - Projects: projects.md
  - Resume: resume.md
  - Contact: contact.md

markdown_extensions:
  - toc:
      permalink: false
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  generator : false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kamranali
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/kamranali
      footer: "© 2025 Kamran Ali"
      footer: Kamran Ali

extra_css:
  - stylesheets/extra.css  # Optional: use if you want custom styles

plugins:
- glightbox:
    thumbnail: true
    thumbnail_size: 200px
- search: # Optional: use if you want a search bar
